# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" #"default", "air", "aqua", "contrast", "dirt", "neon", "mint", "plum", "sunrise"


# Site Settings
locale                   : "en-US"
title                    : " Michel Muñoz Castro"
title_separator          : "-"
subtitle                 : "Personal website" #"Subtitle" # site tagline that appears below site title in masthead
name                     : "Michel Muñoz Castro"
email                    : "michelmzco@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  "Southern chilean computer engineer."
#url: "https://www.michelmzc.com"
#baseurl: "/"

#twitter_username: username
#github_username: michelmzc

search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Santiago

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  #- jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Michel Muñoz Castro"
  avatar : "/assets/images/michel.jpg"
  bio    : "Southern Chilean Computer Science Engineer"
  links:
    #- label: "Website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://www.michelmzc.com"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/michelamzc"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michelmzc"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/michelmzc"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/michel-mu%C3%B1oz-castro-a08b21215/"


footer:
  links:
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michelmzc"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/michelmzc"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/michel-mu%C3%B1oz-castro-a08b21215/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  #_portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

